declare module 'callbag-basics-esmodules'
declare module 'callbag-websocket'
declare module 'callbag-observe'
declare module 'callbag-types'
declare module 'callbag-last'
declare module 'decoder1090-c'
